language: go
os:
  - linux
  - osx
go:
  - 1.9.x
  - tip
go_import_path: github.com/purpleidea/mgmt
sudo: true
dist: trusty
before_install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt update; fi
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch --unshallow
install: 'make deps'
script: 'make test'
matrix:
  fast_finish: false
  allow_failures:
    - go: tip
    - os: osx
notifications:
  irc:
    channels:
      - "irc.freenode.net#mgmtconfig"
    template:
      - "%{repository} (%{commit}: %{author}): %{message}"
      - "More info : %{build_url}"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
  email:
    recipients:
      - travis-ci@shubin.ca
    on_failure: change
    on_success: change
